# update npm packages
version: 2
updates:
  - package-ecosystem: "npm"
    vendor: true
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    open-pull-requests-limit: 3
